/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashboardSidebar: typeof import('./src/components/Dashboard/DashboardSidebar.vue')['default']
    FirstComponent: typeof import('./src/components/FirstComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDrawer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}

// For TSX support
declare global {
  const DashboardSidebar: typeof import('./src/components/Dashboard/DashboardSidebar.vue')['default']
  const FirstComponent: typeof import('./src/components/FirstComponent.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UAuthForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
  const UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
  const UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  const UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
  const UDashboardNavbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
  const UDashboardPanel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
  const UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
  const UDashboardSidebarCollapse: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
  const UDrawer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue')['default']
  const UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  const UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
  const UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
  const UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  const UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_8db7a8e2e5990586ce92c0e9ce4b546c/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
  const UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_e64fb39f037ff0af0e71bfcd993e8bf6/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
}